### ISSUE TITLE
Last versions of the plugin are not published to packages repositories

### ISSUE THREAD

**Issue by Dinduks** [play2war/play2-war-plugin#267] opened 2014-09-24 12:45 UTC
Including _play2-war-plugin_2.11_0.13/1.3-beta2/play2-war-plugin-1.3-beta2.pom_.

Thanks.

**Comment by dlecan** [comment] 2014-09-24 15:12
What di you mean by "packages repositories" ? Maven central ?

I remember it was not impossible to publish SBT plugins to Maven central because artifact layout is incompatible with their policies.

**Comment by Dinduks** [comment] 2014-09-24 15:39
I mean Sonata, Maven Central and Typesafe's repos.
SBT checks in two of these by default (can't check which ones are right now as I'm not in front my computer). 

On September 24, 2014 5:12:43 PM CEST, Damien Lecan notifications@github.com wrote:

> What di you mean by "packages repositories" ? Maven central ?
> 
> I remember it was not impossible to publish SBT plugins to Maven
> central because artifact layout is incompatible with their policies.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/play2war/play2-war-plugin/issues/267#issuecomment-56685135

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dlecan** [comment] 2014-09-24 19:11
SBT community plugins are published in Scala SBT repo.
For Play2War:
http://repo.scala-sbt.org/scalasbt/simple/sbt-plugin-releases/com.github.play2war/play2-war-plugin/

There is no Scala 2.11 plugin, as Play's one is only available for Scala 2.10:
http://repo.typesafe.com/typesafe/simple/ivy-releases/com.typesafe.play/sbt-plugin/

**Comment by Dinduks** [comment] 2014-09-24 21:19
I don't understand, in the README it says that the _1.3-beta2_ supports _Play 2.3.2+_. 
Anyway, would you please publish it? It's very convenient to use, especially with people new to Scala.

**Comment by Dinduks** [comment] 2014-09-28 12:47
I tried building _play2-war-plugin_ myself, but since a _build.sbt_ is lacking on the root, I just created one and put _scalaVersion := "2.11.2"_ in it. Problem, that publishes in `/Users/xxx/.ivy2/local/default/play2-war-plugin_2.11/` instead of `/Users/xxx/.ivy2/local/com.github.play2war/play2-war-plugin/scala_2.11/sbt_0.13/1.3-beta2/` where SBT looks by default (`addSbtPlugin(…)`). 

Can you help me with that please?

**Comment by dlecan** [comment] 2014-09-28 19:32
To help to do what ? There is no Scala 2.11 plugin for Play2War because there no Scala 2.11 plugin for Play itself.

What are you trying to do ?

**Comment by Dinduks** [comment] 2014-09-28 19:51
> there no **Scala 2.11 plugin** for Play itself

A plugin to do what? I think I'm missing here, Play works fine with Scala 2.11.

I'm trying to build _play2-war-plugin_ with Scala 2.11.

**Comment by dlecan** [comment] 2014-11-21 20:53
To be clear : Play Framework provides two main components:
- a runtime
- a plugin for sbt

Play2War is an extension for Play sbt plugin.

For Play 2.3 and 2.4, the Play plugin is only available for Scala 2.10, even if Play runtime is also available for Scala 2.11.
So we can't provide any Play2War plugin for Scala 2.11.

Your first request was: play2-war-plugin_**2.11**_0.13/1.3-beta2/play2-war-plugin-1.3-beta2.pom
We can't publish such version of the plugin.

**Comment by jawshooah** [comment] 2015-01-16 22:20
@dlecan I don't understand; in `README.md`, in the very first paragraph is the line

```
Play 2.3.2+         : 1.3-beta2 (Scala 2.10 & 2.11)
```

Are you saying that the `& 2.11` bit is inaccurate?

Also, I am using the Play SBT plugin with Scala 2.11.4, and everything is working fine:

``` sbt
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.7")
```

**Comment by dlecan** [comment] 2015-01-17 20:20
> Are you saying that the & 2.11 bit is inaccurate?

To be clearer : Play Framework provides two main components:
- a runtime: available for Scala 2.10 and 2.11
- a plugin for sbt: only available for Scala 2.10

So, the same for Play2War: 
- a Play2War runtime: available for Scala 2.10 and 2.11
- a Play2War plugin for sbt: only available for Scala 2.10

**Comment by jawshooah** [comment] 2015-01-17 23:44
I understand what you're saying, but I haven't had any problems using the Play plugin for sbt with Scala 2.11 (see previous comment). I also haven't been able to find anything in the [docs](https://www.playframework.com/documentation/2.3.7/Migration23) to suggest that the plugin is not compatible with Scala 2.11.

**Comment by yanns** [comment] 2015-01-21 13:29
@jawshooah sbt uses only Scala 2.10, even if your project uses Scala 2.11.
It is quite confusing I know... ;)

Also the SBT plugin is only published with Scala 2.10, as SBT only supports Scala 2.10.
And the runtime is published with Scala 2.10 & 2.11 and is compatible with the Play Runtime that can be used with Scala 2.10 & Scala 2.11.

**Comment by ikester** [comment] 2015-02-19 03:22
How do you build the project so that the plugin is compiled for Scala 2.10 and the runtime for 2.11?

I cloned the repo and ran `sbt publish-local` but it only generates files for Scala 2.10.

If I then try to run the 'war' target on a new Play 2.3.8 app I get the following:

```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-core-servlet30_2.11;1.3-beta3-SNAPSHOT: not found
```

I could get it working by commenting out the following line in `build.sbt`:

```
//scalaVersion := "2.11.1"
```

But it would be nice to be able to build the Play app with 2.11.

**Comment by yanns** [comment] 2015-02-19 07:55
Your problem is different, try to remove the `-SNAPSHOT`.
Please check the front-page to know which version you should use: https://github.com/play2war/play2-war-plugin

I _am_ using the war plugin with a Play application with scala 2.11.
Also I know it works.

SBT itself uses scala 2.10 to run. But this is a detail.
SBT and Play are 2 different runtimes, and each uses a different version of scala.

**Comment by ikester** [comment] 2015-02-19 18:30
The problem is that I'm trying to deploy an app built with Play 2.3.8 and I'm encountering this bug:
https://github.com/play2war/play2-war-plugin/issues/280

Since the last version posted to the public repos is 1.3-beta2 (AFAIK) I need to build the project myself with the fix committed a few days ago.

How can I build and publish-local and make sure I get the full output?

**Comment by dlecan** [comment] 2015-02-20 06:43
Just wait a few hours, I will release a new version this weekend.

**Comment by yanns** [comment] 2015-02-20 08:49
@ikester If you want to publish the war plugin locally, please follow the instructions under: https://github.com/play2war/play2-war-plugin/wiki/How-to-help#build-and-publish-plugin-and-core-runtime-in-local-repository

I added a line for Scala 2.11.

And please tell us if you find a problem, before we release a new version ;)
Thanks!

**Comment by ikester** [comment] 2015-02-20 23:27
Thanks. Building by following those steps worked by publishing both versions (Scala 2.10 & 2.11) to my local Ivy repo.

Whenever you publish beta3 to the public repos I'll try again with those.

Thanks again!

**Closed as completed** 2015-02-22 20:54 UTC
