### ISSUE TITLE
[Tomcat 7x] Upload timeout?

### ISSUE THREAD

**Issue by marcosinigaglia** [play2war/play2-war-plugin#75] opened 2012-08-16 12:40 UTC
I think i have a timeout problem on file upload. 

The exception is "java.lang.IllegalStateException: The request associated with the AsyncContext has already completed processing.".

I use this configuration for connector:

<Connector port="18080" protocol="org.apache.coyote.http11.Http11NioProtocol"
               connectionTimeout="150000"
               asyncTimeout="150000"
               address="xxxx"
               redirectPort="8443" />

The same file uploaded from the server (more faster) didn't  give problems.

Any ideas?

**Comment by dlecan** [comment] 2012-08-16 13:02
Play2war version? 
Tomcat version? 
Full stacktrace? 
All file sizes?

**Comment by marcosinigaglia** [comment] 2012-08-16 13:06
Play2war 0.7
Tomcat 7.0.27
The file is 1.2mb

2012-08-16 14:16:56,337 - [ERROR] - from akka.dispatch.Dispatcher in play-akka.actor.default-dispatcher-16 
The request associated with the AsyncContext has already completed processing.
java.lang.IllegalStateException: The request associated with the AsyncContext has already completed processing.
    at org.apache.catalina.core.AsyncContextImpl.check(AsyncContextImpl.java:438) ~[catalina.jar:7.0.27]
    at org.apache.catalina.core.AsyncContextImpl.getRequest(AsyncContextImpl.java:190) ~[catalina.jar:7.0.27]
    at play.core.server.servlet30.Play2Servlet.getHttpRequest(Play2Servlet30.scala:42) ~[com.github.play2war.play2-war-core-servlet30_2.9.1-0.7.jar:0.7]
    at play.core.server.servlet30.Play2Servlet.getHttpRequest(Play2Servlet30.scala:24) ~[com.github.play2war.play2-war-core-servlet30_2.9.1-0.7.jar:0.7]
    at play.core.server.servlet.Play2Servlet$$anonfun$13.apply(Play2CommonServlet.scala:273) ~[com.github.play2war.play2-war-core-common_2.9.1-0.7.jar:0.7]
    at play.core.server.servlet.Play2Servlet$$anonfun$13.apply(Play2CommonServlet.scala:248) ~[com.github.play2war.play2-war-core-common_2.9.1-0.7.jar:0.7]
    at play.api.libs.concurrent.AkkaPromise$$anonfun$flatMap$1.apply(Akka.scala:58) ~[play.play_2.9.1-2.0.2.jar:2.0.2]
    at play.api.libs.concurrent.AkkaPromise$$anonfun$flatMap$1.apply(Akka.scala:57) ~[play.play_2.9.1-2.0.2.jar:2.0.2]
    at akka.dispatch.Future$$anonfun$onSuccess$1.apply(Future.scala:484) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Future$$anonfun$onSuccess$1.apply(Future.scala:483) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.DefaultPromise.akka$dispatch$DefaultPromise$$notifyCompleted(Future.scala:943) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.DefaultPromise$$anonfun$tryComplete$1$$anonfun$apply$mcV$sp$4.apply(Future.scala:920) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.DefaultPromise$$anonfun$tryComplete$1$$anonfun$apply$mcV$sp$4.apply(Future.scala:920) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at scala.collection.immutable.List.foreach(List.scala:45) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at akka.dispatch.DefaultPromise$$anonfun$tryComplete$1.apply$mcV$sp(Future.scala:920) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Future$$anon$4$$anonfun$run$1.apply$mcV$sp(Future.scala:386) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Future$$anon$4$$anonfun$run$1.apply(Future.scala:378) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Future$$anon$4$$anonfun$run$1.apply(Future.scala:378) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) ~[org.scala-lang.scala-library-2.9.1.jar:na]
    at akka.dispatch.Future$$anon$4.run(Future.scala:378) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:94) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1381) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]

**Comment by marcosinigaglia** [comment] 2012-08-16 13:11
And Play Framework 2.0.2

**Comment by dlecan** [comment] 2012-08-16 15:01
> The same file uploaded from the server (more faster) didn't give problems.

What does that mean ? (twice as fast, 3 times, ...)

Anyway, there is something wrong in the servlet code.

Exception is thrown here :
https://github.com/dlecan/play2-war-plugin/blob/develop/project-code/core/common/src/main/scala/Play2CommonServlet.scala#L273

Exception is thrown because AsyncContext has been recycled and HTTPRequest is "null". AsyncContext is recycled when reponse has been proceed or when a timeout is reached (or ?).

Do you receive the expected response page ?

Possible explanation:
1. file is correctly uploaded
2. response is generated asynchronously and asyncontext is completed (an so request is recycled)
3. closing inputstream from request throws an Exception because asyncontext is completed

It works sometimes because steps 2/ and 3/ are executed in the reverse order.

I need to reproduce to confirm that.

**Comment by marcosinigaglia** [comment] 2012-08-16 15:27
I have no response from this request, the server is the same where the application is loaded so the ulpoad is instantaneous, from my client the upload take about 23 seconds.
I'll try with small files to understand the timeout time.

**Comment by marcosinigaglia** [comment] 2012-08-16 16:09
I think the threshold is about 10 seconds

**Comment by dlecan** [comment] 2012-08-23 15:08
A fix will be available with the next version (0.7.2). I hope it will solve your problem because I was not able to reproduce exactly your issue.

**Comment by marcosinigaglia** [comment] 2012-08-24 11:02
Thanks, i'll try the fix

**Comment by dlecan** [comment] 2012-08-24 14:19
Play2War v0.7.2 is out, including a fix for this issue.

**Comment by marcosinigaglia** [comment] 2012-08-24 15:09
Same exception:

2012-08-24 16:56:25,621 - [ERROR] - from play.core.ActionInvoker in play-akka.actor.default-dispatcher-4 
The request associated with the AsyncContext has already completed processing.
java.lang.IllegalStateException: The request associated with the AsyncContext has already completed processing.
    at org.apache.catalina.core.AsyncContextImpl.check(AsyncContextImpl.java:438) ~[catalina.jar:7.0.27]
    at org.apache.catalina.core.AsyncContextImpl.getResponse(AsyncContextImpl.java:196) ~[catalina.jar:7.0.27]
    at play.core.server.servlet30.Play2Servlet.getHttpResponse(Play2Servlet30.scala:44) ~[com.github.play2war.play2-war-core-servlet30_2.9.1-0.7.2.jar:0.7.2]
    at play.core.server.servlet30.Play2Servlet.getHttpResponse(Play2Servlet30.scala:24) ~[com.github.play2war.play2-war-core-servlet30_2.9.1-0.7.2.jar:0.7.2]
    at play.core.server.servlet.Play2Servlet$$anon$3.handle(Play2CommonServlet.scala:115) ~[com.github.play2war.play2-war-core-common_2.9.1-0.7.2.jar:0.7.2]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:165) ~[play.play_2.9.1-2.0.2.jar:2.0.2]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:115) ~[play.play_2.9.1-2.0.2.jar:2.0.2]
    at akka.actor.Actor$class.apply(Actor.scala:318) ~[com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at play.core.ActionInvoker.apply(Invoker.scala:113) ~[play.play_2.9.1-2.0.2.jar:2.0.2]
    at akka.actor.ActorCell.invoke(ActorCell.scala:626) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.Mailbox.run(Mailbox.scala:179) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:516) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]
    at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [com.typesafe.akka.akka-actor-2.0.2.jar:2.0.2]

**Comment by dlecan** [comment] 2012-08-26 12:56
Exception looks like previous one, but no, they are not exactly the same :-) 

File upload is complete and exception is now thrown when Play server wants to render response. 

Something invalidates Servlet AsynContext and I don't know what. 

I tried to upload udge files (until 500Mb, in around 50s) on Tomcat 7.0.29, with same connector configuration, but I wasn't able to reproduce the issue. 

I don't think Tomcat version is a problem. 

To correctly understand your issue in order to fix it, you will have to test snapshots of Play2War with enhanced logs. Then you'll report logs as feedback. 

Are you ready to do that?

**Comment by marcosinigaglia** [comment] 2012-08-27 07:28
Sure Damien, thanks

**Comment by marcosinigaglia** [comment] 2012-08-27 10:28
Hi, i've seen now that the file has been uploaded correctly but the response still empty.
Where do i have to download the snapshot?

**Comment by dlecan** [comment] 2012-08-27 13:12
Before testing snapshots, I need more informations :)
1. Where is sent the stacktrace ? Log file ? Console ? Have you got a special logger.xml configuration ?
   Can you provide output logs "written" before the stacktrace ?
2. Is it possible to simulate a slow upload with curl ? Curl is a command-line tool to send HTTP request (easy to install on Linux/Mac, a bit harder on Windows).
   If you don't know what is curl, forget this question.
   If you know, you can simulate a slow upload with the following command:
   `curl -F file=@/paht/to/file/to/upload -w "\nTIME: %{time_total} sec\n" --limit-rate 10k http://yourhost/uploadpath`
   Where `file` is the html field name associated with the file to upload and `10k` the speed limit to apply per second.
   If you upload a 1,2Mb file, upload should be around 120s (~1,2*1024/10).
   Do you have the same exception ?

**Comment by marcosinigaglia** [comment] 2012-08-27 16:31
The log is in on a separated file with a special logger.xml so i can retrieve all the messages.
Tomorrow i'll try the test with curl.

**Comment by dlecan** [comment] 2012-08-28 11:39
I've published Play2war artifacts as snapshots, with enhanced logs (as info level).

Setup :
- In `YOUR_PROJECT/project/plugins.sbt`, replace `https://repository-play-war.forge.cloudbees.com/release` by `https://repository-play-war.forge.cloudbees.com/snapshot`
- In `YOUR_PROJECT/project/Build.scala`, replace your actual Play2War version by `0.8-issue75-SNAPSHOT`
- Build as usual
- Reproduce your problem
- Send back logs here

**Comment by marcosinigaglia** [comment] 2012-08-28 18:13
Ok, this is the point:

2012-08-28 20:04:49,348 - [DEBUG] - from org.apache.jasper.compiler.JspRuntimeContext in ContainerBackgroundProcessor[StandardEngine[Catalina]] 
Checking JSPs for unload in context [], JSP count: 0 queue length: -1

2012-08-28 20:04:59,359 - [DEBUG] - from org.apache.jasper.compiler.JspRuntimeContext in ContainerBackgroundProcessor[StandardEngine[Catalina]] 
Checking JSPs for unload in context [], JSP count: 0 queue length: -1

2012-08-28 20:05:02,536 - [INFO] - from play in ajp-apr-18009-exec-31 
onTimeout: org.apache.catalina.connector.RequestFacade@58e4df82
java.lang.Exception: null
    at play.core.server.servlet30.AsyncListener$$anonfun$onTimeout$2.apply(Play2Servlet30.scala:61) ~[com.github.play2war.play2-war-core-servlet30_2.9.1-0.8-issue75-SNAPSHOT.jar:0.8-issue75-SNAPSHOT]
    at play.core.server.servlet30.AsyncListener$$anonfun$onTimeout$2.apply(Play2Servlet30.scala:61) ~[com.github.play2war.play2-war-core-servlet30_2.9.1-0.8-issue75-SNAPSHOT.jar:0.8-issue75-SNAPSHOT]
    at play.api.LoggerLike$class.info(Logger.scala:99) [play.play_2.9.1-2.0.2.jar:2.0.2]
    at play.api.Logger.info(Logger.scala:147) [play.play_2.9.1-2.0.2.jar:2.0.2]
    at play.core.server.servlet30.AsyncListener.onTimeout(Play2Servlet30.scala:61) [com.github.play2war.play2-war-core-servlet30_2.9.1-0.8-issue75-SNAPSHOT.jar:0.8-issue75-SNAPSHOT]
    at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:45) [catalina.jar:7.0.27]
    at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:118) [catalina.jar:7.0.27]
    at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:292) [catalina.jar:7.0.27]
    at org.apache.coyote.ajp.AbstractAjpProcessor.asyncDispatch(AbstractAjpProcessor.java:475) [tomcat-coyote.jar:7.0.27]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:559) [tomcat-coyote.jar:7.0.27]
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1814) [tomcat-coyote.jar:7.0.27]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source) [na:1.6.0_33]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.6.0_33]
    at java.lang.Thread.run(Unknown Source) [na:1.6.0_33]

2012-08-28 20:05:02,543 - [INFO] - from play in ajp-apr-18009-exec-31 
onError: org.apache.catalina.connector.RequestFacade@58e4df82

2012-08-28 20:05:02,543 - [INFO] - from play in ajp-apr-18009-exec-31 
onComplete: org.apache.catalina.connector.RequestFacade@58e4df82

**Comment by marcosinigaglia** [comment] 2012-08-28 18:18
Using only curl the other exception disappear...probably are the follow request with browser that fire that.

**Comment by dlecan** [comment] 2012-08-29 08:18
Apache AJP connector request is timed out!
This is a socket timeout, generated in Tomcat code: https://github.com/apache/tomcat70/blob/efa0e79f82f17880c0d7427918bc34a83243dfa6/java/org/apache/tomcat/util/net/AprEndpoint.java#L1063

You didn't noticed you were using AJP connector instead of standard HTTP connector.
So I discoverd this: http://serverfault.com/questions/419529/tomcat-asynctimeout-and-apr-connector
Tomcat doesn't seem to respect `asynctimeout` configuration.

We can try to force it through Java code to check if issue comes from that. I deployed new snapshots of Play2War which [disable asynctimeout](https://github.com/dlecan/play2-war-plugin/commit/191775bde2a8d8ded6254636fd60a6bd594c0916).

**Comment by marcosinigaglia** [comment] 2012-08-29 12:37
Works, thanks a lot. Sorry I forgot to tell you about the AJP connector.
Again, thanks a million.

**Comment by dlecan** [comment] 2012-08-29 13:12
Play2War 0.7.3 with a fix for this issue has been released.

**Closed as completed by dlecan** 2012-08-29 13:12 UTC
Labels: bug, core
