### ISSUE TITLE
Runtime error in play 2.3.3: SimpleResult is still used in play2-war-plugin 1.3-beta2 

### ISSUE THREAD

**Issue by dongyu1** [play2war/play2-war-plugin#269] opened 2014-10-02 02:25 UTC
SimpleResult is deprecated in play 2.3.0+. 
Play2-war-plugin 1.3-beta2 is supposed to be compatiable to play 2.3.2+.
But SimpleResult is still used in the following two files:
(1) play2-war-plugin-1.3-beta2\project-code\core\servlet31\src\main\scala\play\core\server\servlet31\RequestHandler31.scala
(2) play2-war-plugin-1.3-beta2\project-code\core\common\src\main\scala\play\core\server\servlet\RequestHandler.scala

I can build the war with play 2.3.3. successfully. But there is a runtime error as follows
java.lang.NoClassDefFoundError: play/api/mvc/SimpleResult

> -play.core.server.servlet.Play2GenericServletRequestHandler$$anonfun$22$$anonfun$apply$27.apply(RequestHandler.scala:400)
> ---at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)

The reason is: in play 2.3.3, SimpleResult is not supported.
Please advice. Thanks..

**Comment by yanns** [comment] 2014-10-02 08:04
Are you sure you use play 2.3.3?

I use the 2.3.4 version with the play2war plugin without any problems.
SimpleResult is deprecated in play 2.3 but will not be removed until play 2.4.

**Comment by dongyu1** [comment] 2014-10-02 15:01
Yes. I used play 2.3.3 and play2-maven-plugin 1.0.0-alpha8
I searched the play_2.10-2.3.3.jar and didin't find play.api.mvc.SimpleResult is there. Do you know which jar SimpleResult should be in? Thanks.

**Comment by dongyu1** [comment] 2014-10-02 15:12
I checked play_2.10-2.2.3.jar and SimpleResult.class can be found there.
As from 2.3.3, the SimpleResult is changed back by Result. The solution is: 
Replace all SimpleResult with Result
in the following two files: 
(1) play2-war-plugin-1.3-beta2\project-code\core\servlet31\src\main\scala\play\core\server\servlet31\RequestHandler31.scala
(2) play2-war-plugin-1.3-beta2\project-code\core\common\src\main\scala\play\core\server\servlet\RequestHandler.scala
and recompile a customized version of play2-war-plugin 1.3-beta2.
I can recompile successfully. Please let me know whether that change will break any functionality. Thanks.

**Comment by yanns** [comment] 2014-10-02 15:17
no it does not break anything.
The problem is not about the patch.

It is about understanding what's happening, as I am using the same configuration without any problem.
And I am sure that play 2.3.3 contains SimpleResult. Check the source: https://github.com/playframework/playframework/blob/2.3.3/framework/src/play/src/main/scala/play/api/mvc/package.scala#L37

Are you sure the maven plugin does not break the dependencies?

**Comment by dlecan** [comment] 2014-10-03 08:13
Please raise an issue to Maven Play2 plugin, as we cannot reproduce it.
Link it here for traceability.

**Comment by dongyu1** [comment] 2014-10-03 15:55
Yanns, You are right. SimpleResult is still in play_2.10-2.2.3.jar and it is renamed to: package$SimpleResult$.class. The issue is solved. Why the error happens: is another project (play 2.3.3) mistakenly used play2war-plugin-1.2. Please close this issue. Thank you.

**Comment by yanns** [comment] 2014-10-04 09:07
Thanks for taking the time to find the issue and for the explanation.
I close the issue.

And in master, I fix the usage of deprecated `SimpleResult`: https://github.com/play2war/play2-war-plugin/commit/df81e687a8e8ebfaf9a2e5b61601eea333e65bf0

**Closed as completed by yanns** 2014-10-04 09:07 UTC
