### ISSUE TITLE
Chunked result : enumerator/iteratee not stopped when an exception is thrown

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#89] opened 2012-09-25 08:17 UTC
> still carries with the processing. This results in unneccessary db load and a lot of these exceptions in the log.
> `2012-09-25 08:36:11,287 DEBUG play  - ClientAbortException:  java.net.SocketException: Broken pipe`
> It doesnt look like a problem when using play netty directly.

Exception seen in your log file is probably this one :
https://github.com/dlecan/play2-war-plugin/blob/develop/project-code/core/common/src/main/scala/Play2CommonServlet.scala#L216

Exception may not be correctly handled and enumerator/iteratee is not stopped.

**Comment by sejensen** [comment] 2012-09-25 11:13
That does look like a possible place for the error to appear. My enumerator fromcallback never gets this exception and thus cannot stop the processing.

Is it difficult to fix? If not when do you think it can be fixed?. 

If you want me to try a hotfix out just say so.
Kind regards
Steffen

**Comment by dlecan** [comment] 2012-09-25 13:03
I am able to reproduce the issue when cutting client connection with a ChunkedResult.

> 2012-09-xx 14:49:48,970 - [DEBUG] - from play in promise-akka.actor.default-dispatcher-34
> ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error

Now I will look at where I can trap the exception to stop the iteratee ...

**Comment by dlecan** [comment] 2012-09-25 13:29
Fixed on 0.8, not for 0.7.x

**Comment by sejensen** [comment] 2012-09-25 14:57
Cool!
When do you expect 0.8 will be released?
Thanks
Steffen

**Comment by dlecan** [comment] 2012-09-25 19:55
> When do you expect 0.8 will be released?

Still too much work on 0.8.
I will release a 0.7.4 with this fix only.

**Comment by sejensen** [comment] 2012-09-25 20:04
Thank you very much

Kind regards
Steffen

**Comment by dlecan** [comment] 2012-09-26 12:22
I just deploy 0.7.4-SNAPSHOT in http://repository-play-war.forge.cloudbees.com/snapshot/

Can you test it ?

**Comment by sejensen** [comment] 2012-09-26 12:24
Yes thank you

I will test it now

**Comment by sejensen** [comment] 2012-09-26 13:52
Hi again

Tested it on our jboss server and now the streaming stops correctly after
the ClientAbortException.

Thank you very much
Steffen

**Comment by dlecan** [comment] 2012-09-26 14:01
Something more to do about #87 ? (response mixed-up)
May I release this 0.7.4 ?

**Comment by sejensen** [comment] 2012-09-26 14:13
Hi damian #87 stopped showing when opgrading to 0.7.3 but the diff you sent
me do not solve stuff related to response mixups. So for now it is solved
but I am bit afraid that I do not know the reason.

We are going live friday so perhaps and are a bit busy. But I will try
0.7.2 again next week to see if I can reproduce my streaming with other
request mix-ups, just to verify if that was the solution)

I have not found any issues with 0.7.4 but have only tested it for an hour
or two.

Its ok from here to release it.

Kind regards
Steffen

**Comment by dlecan** [comment] 2012-09-26 19:43
Play2War 0.7.4 including a fix for this issue has been released.

**Closed as completed** 2012-09-28 14:02 UTC
Labels: bug, core
