### ISSUE TITLE
Exploded Jar function doesn't work

### ISSUE THREAD

**Issue by azuken** [play2war/play2-war-plugin#224] opened 2014-02-18 15:24 UTC
I use Play 2.2.1 with Scala 2.10 and sbt 0.13.1. Play2War plugin works fine, but I want to get my custom conf after have deployed war.

So I've set Play2WarKeys.explodedJar := true, but nothing happends : Play project jar is in lib directory, but no classes directory

(I use a Build.sbt, not Build.scala)

Play2War version : 1.2-beta4

**Comment by dlecan** [comment] 2014-02-18 16:32
You're right, that's a regression.

**Comment by azuken** [comment] 2014-02-19 08:27
It will be corrected soon ? (next release ?)

**Comment by dlecan** [comment] 2014-02-19 09:50
I hope so.
Sure, it will be fixed for 1.2. So probably for next 1.2 beta.

**Comment by ritu-p** [comment] 2014-05-12 07:43
Hi is this issue fixed in any of the latest versions?

**Comment by dlecan** [comment] 2014-05-12 09:14
This issue is still opened, doesn't it ?

**Comment by ritu-p** [comment] 2014-05-12 09:49
Sorry,
I didnt notice the status
Thanks for you time and great work

**Comment by benlwong** [comment] 2014-05-13 19:23
I also would really like to see this fixed.  I am not sure if I am looking at the right part of the source code, but it appears the code to explode the jar is commented out.  Probably not as simple as uncommenting the code...

**Comment by yanns** [comment] 2014-05-13 19:33
2014-05-13 21:23 GMT+02:00 Ben Wong notifications@github.com:

> I also would really like to see this fixed. I am not sure if I am looking
> at the right part of the source code, but it appears the code to explode
> the jar is commented out. Probably not as simple as uncommenting the code...
> 
> That would be great! ;)
> No, the migration to play 2.2 was difficult, and this code could not be
> used directly.
> If you are motivated, you can try to implement this. It requires a good
> comprehension of sbt and the native packager plugin:
> https://github.com/sbt/sbt-native-packager

Can you maybe explain why this feature is so important for you? I
personally don't see any value in it.

**Comment by benlwong** [comment] 2014-05-13 19:51
I actually was trying to see if I can fix it, but realized the code (after cloning it) is written in Scala and sbt.  I have no experience in Scala at all, so it is going to take me a long time if I decide to attempt it.

This is important because of Issue #179.

Damien recommended that I have the WAR exploded because Tomcat loads resources (jars) in alphabetical order.  Hence, the class loader wasn't picking up my logger.xml file in my app jar (called portal.jar).  Instead, it was picking up the default logger.xml file in play*.jar.

If there is a better solution to the above problem, I would not need the jar exploded.

Thanks,
Ben

**Comment by yanns** [comment] 2014-05-13 20:01
I understand.
I deploy the logger.xml always separated to the war, to be able to change quickly the log debug without deploying a new war.
For this, I start tomcat with the following setenv.sh:

```
export JAVA_OPTS="-Dconfig.file=/opt/tomcat/conf/application.conf -Dlogback.configurationFile=/opt/tomcat/conf/logback.xml -Dlogger.file=/opt/tomcat/conf/logback.xml"
```

(`-Dconfig.file=...` is not mandatory for setting the logger.xml)

**Comment by benlwong** [comment] 2014-05-13 20:11
I will see if I can work around it.  However, in production, we have a few war apps running.  So one logger.xml file might not be ideal.  You will have to update it and source control it somehow to work for all apps.

**Comment by yanns** [comment] 2014-06-10 06:14
https://github.com/play2war/play2-war-plugin/tree/issue-%23224-exploded-jar

**Closed as completed** 2014-06-10 09:13 UTC
Labels: bug, plugin

**Comment by dlecan** [comment] 2014-06-23 08:06
Play2War 1.2 final has been released with a fix for this issue
Enjoy !

**Comment by benlwong** [comment] 2014-06-23 12:32
Thanks for fixing this issue.  Much appreciated!
